# tomcat
server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8080"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}



# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: fws1656621300
      database: mango
#开放检查端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
